### ISSUE TITLE
Light/dark mode

### ISSUE THREAD

**Issue by maseiler** [maseiler/avh-booking-system#103]
Allow setting light or dark mode. [This](https://github.com/jgthms/bulma/issues/2342) could be helpful.

Possible future work:
- enable/disable automatically based on time

**Comment by ebert-l** [comment]
Improvement on the automatic scheme-selection would be if it does not simply rely on a given time, but on the real sunrise and sunset times for the current GEO-Location.
May be possible with [some weather APIs](https://openweathermap.org/api)
But this solution requires a constant internet connection.
